name: Build docs

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - secretflow
          - spu
          - heu
          - interconnection
          - scql
          - kuscia

    steps:
      - uses: actions/checkout@v3

      - name: Create temporary directory
        run: |
          rm -rf ${{ github.workspace }}/build
          mkdir -p ${{ github.workspace }}/build
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: secretflow/${{ matrix.project }}
          path: ${{ github.workspace }}/build/${{ matrix.project }}
      - name: Patch config
        run: |
          cp -rf ${{ github.workspace }}/patches/${{ matrix.project }}/* ${{ github.workspace }}/build/${{ matrix.project }}/

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.x'
          cache: 'pip'
          cache-dependency-path: |
            build/${{ matrix.project }}/requirements.txt
            build/${{ matrix.project }}/docs/requirements.txt

      - name: Install Python dependencies
        working-directory: build/${{ matrix.project }}
        run: |
          python -m pip install --upgrade pip

      - name: "Get project's commit SHA"
        id: get-project-sha
        working-directory: build/${{ matrix.project }}
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: 'Install pandoc'
        run: |
          curl -sSL https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb -o pandoc.deb
          sudo dpkg -i pandoc.deb
          rm pandoc.deb

      - name: 'Build docs'
        working-directory: build/${{ matrix.project }}
        run: ./build_docs.sh

      - name: 'Copy artifacts'
        run: |
          rm -rf ${{ github.workspace }}/artifacts/${{ matrix.project }}
          mkdir -p ${{ github.workspace }}/artifacts/${{ matrix.project }}/latest
          cp -rf \
            ${{ github.workspace }}/build/${{ matrix.project }}/docs/_build/mdx/* \
            ${{ github.workspace }}/artifacts/${{ matrix.project }}/latest/

      # Generate GitHub token for changesets/action
      # Using https://github.com/secretflow/bot
      # This allows changesets/action to create a release PR using the bot's identity
      # Token goes into env. See action for details
      - name: Generate GitHub token
        uses: wow-actions/use-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: 'Create pull request'
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            artifacts/${{ matrix.project }}/latest
          commit-message: 'chore(${{ matrix.project }}): Update docs to ${{ steps.get-project-sha.outputs.sha }}'
          branch: 'docs/${{ matrix.project }}'
          delete-branch: true
          title: 'chore(${{ matrix.project }}): Update docs'
          token: ${{ env.BOT_TOKEN }}
          body: |
            This PR updates documentation artifacts for ${{ matrix.project }}.

            Built from [`${{ steps.get-project-sha.outputs.sha }}`][commit]

            [commit]: https://github.com/secretflow/${{ matrix.project }}/commit/${{ steps.get-project-sha.outputs.sha }}
